#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SamsGear.Resource", IsApplication=true)]

namespace SamsGear
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::SamsGear.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::SamsGear.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060031
			public const int AliceBlue = 2131099697;
			
			// aapt resource value: 0x7f060027
			public const int AntiqueWhite = 2131099687;
			
			// aapt resource value: 0x7f060081
			public const int Aqua = 2131099777;
			
			// aapt resource value: 0x7f060066
			public const int Aquamarine = 2131099750;
			
			// aapt resource value: 0x7f06002f
			public const int Azure = 2131099695;
			
			// aapt resource value: 0x7f06002c
			public const int Beige = 2131099692;
			
			// aapt resource value: 0x7f060012
			public const int Bisque = 2131099666;
			
			// aapt resource value: 0x7f060090
			public const int Black = 2131099792;
			
			// aapt resource value: 0x7f060010
			public const int BlanchedAlmond = 2131099664;
			
			// aapt resource value: 0x7f06008c
			public const int Blue = 2131099788;
			
			// aapt resource value: 0x7f06005f
			public const int BlueViolet = 2131099743;
			
			// aapt resource value: 0x7f060053
			public const int Brown = 2131099731;
			
			// aapt resource value: 0x7f060039
			public const int BurlyWood = 2131099705;
			
			// aapt resource value: 0x7f060071
			public const int CadetBlue = 2131099761;
			
			// aapt resource value: 0x7f060067
			public const int Chartreuse = 2131099751;
			
			// aapt resource value: 0x7f060043
			public const int Chocolate = 2131099715;
			
			// aapt resource value: 0x7f06001c
			public const int Coral = 2131099676;
			
			// aapt resource value: 0x7f060070
			public const int CornflowerBlue = 2131099760;
			
			// aapt resource value: 0x7f06000c
			public const int Cornsilk = 2131099660;
			
			// aapt resource value: 0x7f06003c
			public const int Crimson = 2131099708;
			
			// aapt resource value: 0x7f060082
			public const int Cyan = 2131099778;
			
			// aapt resource value: 0x7f06008e
			public const int DarkBlue = 2131099790;
			
			// aapt resource value: 0x7f060088
			public const int DarkCyan = 2131099784;
			
			// aapt resource value: 0x7f06004b
			public const int DarkGoldenrod = 2131099723;
			
			// aapt resource value: 0x7f060052
			public const int DarkGray = 2131099730;
			
			// aapt resource value: 0x7f06008b
			public const int DarkGreen = 2131099787;
			
			// aapt resource value: 0x7f060048
			public const int DarkKhaki = 2131099720;
			
			// aapt resource value: 0x7f06005d
			public const int DarkMagenta = 2131099741;
			
			// aapt resource value: 0x7f060072
			public const int DarkOliveGreen = 2131099762;
			
			// aapt resource value: 0x7f06001b
			public const int DarkOrange = 2131099675;
			
			// aapt resource value: 0x7f060056
			public const int DarkOrchid = 2131099734;
			
			// aapt resource value: 0x7f06005e
			public const int DarkRed = 2131099742;
			
			// aapt resource value: 0x7f060036
			public const int DarkSalmon = 2131099702;
			
			// aapt resource value: 0x7f06005b
			public const int DarkSeaGreen = 2131099739;
			
			// aapt resource value: 0x7f060075
			public const int DarkSlateBlue = 2131099765;
			
			// aapt resource value: 0x7f06007b
			public const int DarkSlateGray = 2131099771;
			
			// aapt resource value: 0x7f060086
			public const int DarkTurquoise = 2131099782;
			
			// aapt resource value: 0x7f060058
			public const int DarkViolet = 2131099736;
			
			// aapt resource value: 0x7f060020
			public const int DeepPink = 2131099680;
			
			// aapt resource value: 0x7f060087
			public const int DeepSkyBlue = 2131099783;
			
			// aapt resource value: 0x7f06006e
			public const int DimGray = 2131099758;
			
			// aapt resource value: 0x7f06007f
			public const int DodgerBlue = 2131099775;
			
			// aapt resource value: 0x7f06004c
			public const int FireBrick = 2131099724;
			
			// aapt resource value: 0x7f06000a
			public const int FloralWhite = 2131099658;
			
			// aapt resource value: 0x7f06007d
			public const int ForestGreen = 2131099773;
			
			// aapt resource value: 0x7f060021
			public const int Fuchsia = 2131099681;
			
			// aapt resource value: 0x7f06003b
			public const int Gainsboro = 2131099707;
			
			// aapt resource value: 0x7f060029
			public const int GhostWhite = 2131099689;
			
			// aapt resource value: 0x7f060016
			public const int Gold = 2131099670;
			
			// aapt resource value: 0x7f06003e
			public const int Goldenrod = 2131099710;
			
			// aapt resource value: 0x7f060062
			public const int Gray = 2131099746;
			
			// aapt resource value: 0x7f06008a
			public const int Green = 2131099786;
			
			// aapt resource value: 0x7f060050
			public const int GreenYellow = 2131099728;
			
			// aapt resource value: 0x7f060030
			public const int Honeydew = 2131099696;
			
			// aapt resource value: 0x7f06001d
			public const int HotPink = 2131099677;
			
			// aapt resource value: 0x7f060045
			public const int IndianRed = 2131099717;
			
			// aapt resource value: 0x7f060073
			public const int Indigo = 2131099763;
			
			// aapt resource value: 0x7f060006
			public const int Ivory = 2131099654;
			
			// aapt resource value: 0x7f060032
			public const int Khaki = 2131099698;
			
			// aapt resource value: 0x7f060037
			public const int Lavender = 2131099703;
			
			// aapt resource value: 0x7f06000e
			public const int LavenderBlush = 2131099662;
			
			// aapt resource value: 0x7f060068
			public const int LawnGreen = 2131099752;
			
			// aapt resource value: 0x7f06000b
			public const int LemonChiffon = 2131099659;
			
			// aapt resource value: 0x7f060051
			public const int LightBlue = 2131099729;
			
			// aapt resource value: 0x7f060033
			public const int LightCoral = 2131099699;
			
			// aapt resource value: 0x7f060038
			public const int LightCyan = 2131099704;
			
			// aapt resource value: 0x7f060025
			public const int LightGoldenrodYellow = 2131099685;
			
			// aapt resource value: 0x7f06005a
			public const int LightGreen = 2131099738;
			
			// aapt resource value: 0x7f060041
			public const int LightGrey = 2131099713;
			
			// aapt resource value: 0x7f060018
			public const int LightPink = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int LightSalmon = 2131099674;
			
			// aapt resource value: 0x7f06007e
			public const int LightSeaGreen = 2131099774;
			
			// aapt resource value: 0x7f060060
			public const int LightSkyBlue = 2131099744;
			
			// aapt resource value: 0x7f06006a
			public const int LightSlateGray = 2131099754;
			
			// aapt resource value: 0x7f06004e
			public const int LightSteelBlue = 2131099726;
			
			// aapt resource value: 0x7f060007
			public const int LightYellow = 2131099655;
			
			// aapt resource value: 0x7f060084
			public const int Lime = 2131099780;
			
			// aapt resource value: 0x7f06007a
			public const int LimeGreen = 2131099770;
			
			// aapt resource value: 0x7f060026
			public const int Linen = 2131099686;
			
			// aapt resource value: 0x7f060022
			public const int Magenta = 2131099682;
			
			// aapt resource value: 0x7f060065
			public const int Maroon = 2131099749;
			
			// aapt resource value: 0x7f06006f
			public const int MediumAquamarine = 2131099759;
			
			// aapt resource value: 0x7f06008d
			public const int MediumBlue = 2131099789;
			
			// aapt resource value: 0x7f06004a
			public const int MediumOrchid = 2131099722;
			
			// aapt resource value: 0x7f060059
			public const int MediumPurple = 2131099737;
			
			// aapt resource value: 0x7f060079
			public const int MediumSeaGreen = 2131099769;
			
			// aapt resource value: 0x7f060069
			public const int MediumSlateBlue = 2131099753;
			
			// aapt resource value: 0x7f060085
			public const int MediumSpringGreen = 2131099781;
			
			// aapt resource value: 0x7f060074
			public const int MediumTurquoise = 2131099764;
			
			// aapt resource value: 0x7f060046
			public const int MediumVioletRed = 2131099718;
			
			// aapt resource value: 0x7f060080
			public const int MidnightBlue = 2131099776;
			
			// aapt resource value: 0x7f06002a
			public const int MintCream = 2131099690;
			
			// aapt resource value: 0x7f060011
			public const int MistyRose = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int Moccasin = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int NavajoWhite = 2131099668;
			
			// aapt resource value: 0x7f06008f
			public const int Navy = 2131099791;
			
			// aapt resource value: 0x7f060024
			public const int OldLace = 2131099684;
			
			// aapt resource value: 0x7f060063
			public const int Olive = 2131099747;
			
			// aapt resource value: 0x7f06006c
			public const int OliveDrab = 2131099756;
			
			// aapt resource value: 0x7f060019
			public const int Orange = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int OrangeRed = 2131099679;
			
			// aapt resource value: 0x7f06003f
			public const int Orchid = 2131099711;
			
			// aapt resource value: 0x7f060034
			public const int PaleGoldenrod = 2131099700;
			
			// aapt resource value: 0x7f060057
			public const int PaleGreen = 2131099735;
			
			// aapt resource value: 0x7f06004f
			public const int PaleTurquoise = 2131099727;
			
			// aapt resource value: 0x7f06003d
			public const int PaleVioletRed = 2131099709;
			
			// aapt resource value: 0x7f06000f
			public const int PapayaWhip = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int PeachPuff = 2131099669;
			
			// aapt resource value: 0x7f060044
			public const int Peru = 2131099716;
			
			// aapt resource value: 0x7f060017
			public const int Pink = 2131099671;
			
			// aapt resource value: 0x7f06003a
			public const int Plum = 2131099706;
			
			// aapt resource value: 0x7f06004d
			public const int PowderBlue = 2131099725;
			
			// aapt resource value: 0x7f060064
			public const int Purple = 2131099748;
			
			// aapt resource value: 0x7f060023
			public const int Red = 2131099683;
			
			// aapt resource value: 0x7f060049
			public const int RosyBrown = 2131099721;
			
			// aapt resource value: 0x7f060077
			public const int RoyalBlue = 2131099767;
			
			// aapt resource value: 0x7f06005c
			public const int SaddleBrown = 2131099740;
			
			// aapt resource value: 0x7f060028
			public const int Salmon = 2131099688;
			
			// aapt resource value: 0x7f06002e
			public const int SandyBrown = 2131099694;
			
			// aapt resource value: 0x7f06007c
			public const int SeaGreen = 2131099772;
			
			// aapt resource value: 0x7f06000d
			public const int Seashell = 2131099661;
			
			// aapt resource value: 0x7f060054
			public const int Sienna = 2131099732;
			
			// aapt resource value: 0x7f060047
			public const int Silver = 2131099719;
			
			// aapt resource value: 0x7f060061
			public const int SkyBlue = 2131099745;
			
			// aapt resource value: 0x7f06006d
			public const int SlateBlue = 2131099757;
			
			// aapt resource value: 0x7f06006b
			public const int SlateGray = 2131099755;
			
			// aapt resource value: 0x7f060009
			public const int Snow = 2131099657;
			
			// aapt resource value: 0x7f060083
			public const int SpringGreen = 2131099779;
			
			// aapt resource value: 0x7f060076
			public const int SteelBlue = 2131099766;
			
			// aapt resource value: 0x7f060042
			public const int Tan = 2131099714;
			
			// aapt resource value: 0x7f060089
			public const int Teal = 2131099785;
			
			// aapt resource value: 0x7f060040
			public const int Thistle = 2131099712;
			
			// aapt resource value: 0x7f06001e
			public const int Tomato = 2131099678;
			
			// aapt resource value: 0x7f060078
			public const int Turquoise = 2131099768;
			
			// aapt resource value: 0x7f060035
			public const int Violet = 2131099701;
			
			// aapt resource value: 0x7f06002d
			public const int Wheat = 2131099693;
			
			// aapt resource value: 0x7f060005
			public const int White = 2131099653;
			
			// aapt resource value: 0x7f06002b
			public const int WhiteSmoke = 2131099691;
			
			// aapt resource value: 0x7f060008
			public const int Yellow = 2131099656;
			
			// aapt resource value: 0x7f060055
			public const int YellowGreen = 2131099733;
			
			// aapt resource value: 0x7f060004
			public const int blue = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int grey = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int lightgrey = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int orange = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Beatz = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Black = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Blues = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Bulu = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int buttonshape = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CarolinaBlue = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CartTitle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int CookIslands = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Day = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int DaySelected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int DownArrow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int FiaBotz = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Fobzilla = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int HeatherGrey = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int iFob = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int iFobMini = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Lime = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int MaoriStrong = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Maroon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Maroons = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Navy = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int NiueStrong = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ObeyDeez = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int PayButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Red = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int RoyalBlue = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int SearchButton = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Sell = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int SellSelected = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int SonsSth = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int SportGrey = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Stock = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int StockSelected = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ToaSamoa = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int TokoUso = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int topshaddow = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int UpArrow = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Usos = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Warriors = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int White = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070025
			public const int button1 = 2131165221;
			
			// aapt resource value: 0x7f07000d
			public const int editText1 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int editText2 = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int gridView1 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int imageButton1 = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int imageButton2 = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int imageButton3 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int imageButton4 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int imageButton5 = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int imageButton6 = 2131165202;
			
			// aapt resource value: 0x7f07001d
			public const int imageView1 = 2131165213;
			
			// aapt resource value: 0x7f07001b
			public const int imageView2 = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout1 = 2131165207;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout10 = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout3 = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout4 = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int linearLayout5 = 2131165204;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout6 = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout7 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout8 = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int linearLayout9 = 2131165203;
			
			// aapt resource value: 0x7f070009
			public const int listView1 = 2131165193;
			
			// aapt resource value: 0x7f070015
			public const int myImageView = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int myImageViewText = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int relativeBackground = 2131165184;
			
			// aapt resource value: 0x7f07001f
			public const int relativeLayout1 = 2131165215;
			
			// aapt resource value: 0x7f07000a
			public const int relativelayout = 2131165194;
			
			// aapt resource value: 0x7f070018
			public const int tableLayout1 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int tableRow2 = 2131165209;
			
			// aapt resource value: 0x7f070024
			public const int tableRow3 = 2131165220;
			
			// aapt resource value: 0x7f070020
			public const int textView1 = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int textView2 = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int textView3 = 2131165217;
			
			// aapt resource value: 0x7f070023
			public const int textView4 = 2131165219;
			
			// aapt resource value: 0x7f07001e
			public const int textView5 = 2131165214;
			
			// aapt resource value: 0x7f07001a
			public const int textView6 = 2131165210;
			
			// aapt resource value: 0x7f07001c
			public const int textView7 = 2131165212;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DayPage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FinalizeSellPage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SellPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SingleCartView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SingleColourView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SingleDesignView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SingleOrderView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SingleProductView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SingleStockView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SizeView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int StockPage = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int easyDB = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int app_name = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int hello = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
